spring:
  profiles:
    active:
      - EN
      - cat
      - dev
ernesto:
  username: YmlUserName
  password: YmlPassword
  jdbcurl: YmlUrl

---
spring:
  profiles: prod
ernesto:
  username: YmlProdUserName
  password: YmlProdPassword
  jdbcurl: YmlProdUrl